### ISSUE TITLE
gnmi.GetConfig: unmarshalling error because of unexpected leaf

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ondatra#65] opened 2023-01-10 14:06 UTC
Hi, gnmi.GetConfig fails when there is an additional leaf in the response. The additional fields issue is expected due to the recurring update in oc models.  I think none of the gnmi api should fail due to the additional field. Here is the failure log.

```
I0110 08:52:20.806932   20309 gnmi.go:120] prefix:  {
  target:  "R3-10.85.84.51:2014"
}
path:  {
  origin:  "openconfig"
  elem:  {
    name:  "network-instances"
  }
  elem:  {
    name:  "network-instance"
    key:  {
      key:  "name"
      value:  "VRF-1"
    }
  }
}
type:  CONFIG
encoding:  JSON_IETF
I0110 08:52:20.871681   20309 gnmi.go:237] subscribe ONCE stream closed without sync_response.
I0110 08:52:20.873722   20309 ygnmi.go:250] noncompliant data encountered while unmarshalling: Noncompliance Errors by category:
Path Noncompliance Errors: None
Type Noncompliance Errors:
  Unmarshal json_ietf_val:"{\n \"name\": \"VRF-1\",\n \"config\": {\n  \"name\": \"VRF-1\",\n  \"type\": \"openconfig-network-instance-types:L3VRF\",\n  \"enabled\": true\n },\n \"interfaces\": {\n  \"interface\": [\n   {\n    \"id\": \"TenGigE0/0/0/1/0\",\n    \"config\": {\n     \"id\": \"TenGigE0/0/0/1/0\",\n     \"interface\": \"TenGigE0/0/0/1/0\",\n     \"subinterface\": 0\n    }\n   }\n  ]\n }\n}\n" into origin:"openconfig"  elem:{name:"network-instances"}  elem:{name:"network-instance"  key:{key:"name"  value:"VRF-1"}}: datapoint path "/network-instances/network-instance[name=VRF-1]" (value json_ietf_val:"{\n \"name\": \"VRF-1\",\n \"config\": {\n  \"name\": \"VRF-1\",\n  \"type\": \"openconfig-network-instance-types:L3VRF\",\n  \"enabled\": true\n },\n \"interfaces\": {\n  \"interface\": [\n   {\n    \"id\": \"TenGigE0/0/0/1/0\",\n    \"config\": {\n     \"id\": \"TenGigE0/0/0/1/0\",\n     \"interface\": \"TenGigE0/0/0/1/0\",\n     \"subinterface\": 0\n    }\n   }\n  ]\n }\n}\n") cannot be unmarshalled: rpc error: code = Unknown desc = failed to update struct *oc.NetworkInstance with value json_ietf_val:"{\n \"name\": \"VRF-1\",\n \"config\": {\n  \"name\": \"VRF-1\",\n  \"type\": \"openconfig-network-instance-types:L3VRF\",\n  \"enabled\": true\n },\n \"interfaces\": {\n  \"interface\": [\n   {\n    \"id\": \"TenGigE0/0/0/1/0\",\n    \"config\": {\n     \"id\": \"TenGigE0/0/0/1/0\",\n     \"interface\": \"TenGigE0/0/0/1/0\",\n     \"subinterface\": 0\n    }\n   }\n  ]\n }\n}\n"; parent container network-instance (type *oc.NetworkInstance): JSON contains unexpected field enabled
Value Restriction Noncompliance Errors: None
    gnmi.go:140: Get(t) on dut(R3-10.85.84.51:2014) at &{{NetworkInstance false 0xc0059de4c0 [] 0xc002154120}}: path origin:"openconfig"  elem:{name:"network-instances"}  elem:{name:"network-instance"  key:{key:"name"  value:"VRF-1"}}: value not present
```

This issue causing fp tests (e.g., https://github.com/openconfig/featureprofiles/blob/04860e1abb6139d8135a8f46fa46bb7c8553c128/feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go#L286) that query /network-instance/[name="vrf-name"] to fail.

**Comment by greg-dennis** [comment] 2023-01-10 14:33
@DanG100, was this fixed by https://github.com/openconfig/ygnmi/commit/1dbfbac8c5021bc872d03ab79e8cad1e295378d1?

@mojiiba, are you using ygnmi version  0.7.3?

**Comment by mojiiba** [comment] 2023-01-10 14:35
I am using the latest FP that uses ygnmi version 0.7.3.

**Comment by DanG100** [comment] 2023-01-10 21:55
Can try with ygnmi  v0.7.4 and check if the issue is solved?

**Comment by mojiiba** [comment] 2023-01-10 22:26
@DanG100  thanks a lot, it is resolved, can u please bump the ygni version for FP.

**Comment by greg-dennis** [comment] 2023-01-11 01:57
PR to bump the FP version

**Closed by greg-dennis** 2023-01-11 01:57 UTC
